@startuml

title __KAFFEEMASCHINE's Class Diagram__\n

  namespace kaffeemaschine {
    class kaffeemaschine.AbfallBehaelter {
        + AbfallBehaelter()
        + toString()
        + wartung()
    }
  }
  

  namespace kaffeemaschine {
    abstract class kaffeemaschine.AbstractBehaelter {
        - bezeichner : String
        - fuellstand : double
        - maxFuellMenge : double
        + AbstractBehaelter()
        + getBezeichner()
        + getFuellstand()
        + getMaxFuellMenge()
        + setFuellstand()
        {abstract} + toString()
    }
  }
  

  namespace kaffeemaschine {
    interface kaffeemaschine.IMenu {
        {static} + menu()
        {static} + programmAuswahl()
    }
  }
  

  namespace kaffeemaschine {
    interface kaffeemaschine.IWartbar {
        {abstract} + wartung()
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Kaffeemaschine {
        ~ PROGRAMM_ABBRUCH : int
        ~ WARTUNG : int
        ~ behaelterListe : AbstractBehaelter[]
        {static} ~ betriebsbereit : boolean
        + Kaffeemaschine()
        + getraenkZuebereiten()
        + programmAbbruch()
        + wartungInitiieren()
        + zutatenEntnahme()
        - getraenkAusgeben()
        - pruefeFuellstand()
        - wartenAufWartung()
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Menu {
        {static} + ZEILE_1 : String
        {static} + ZEILE_10 : String
        {static} + ZEILE_2 : String
        {static} + ZEILE_3 : String
        {static} + ZEILE_4 : String
        {static} + ZEILE_5 : String
        {static} + ZEILE_6 : String
        {static} + ZEILE_7 : String
        {static} + ZEILE_8 : String
        {static} + ZEILE_9 : String
        {static} ~ AUSWAHL : String
        + Menu()
        {static} + menu()
        {static} + programmAuswahl()
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Rezept {
        {static} + AuswahlProdukt : String[]
        {static} + getZutatenVerbrauch : double[][]
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.StarteKaffeeMaschine {
        {static} + main()
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.ZutatenBehaelter {
        + ZutatenBehaelter()
        + toString()
        + wartung()
    }
  }
  

  kaffeemaschine.AbfallBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.AbfallBehaelter -up-|> kaffeemaschine.AbstractBehaelter
  kaffeemaschine.AbstractBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.Menu .up.|> kaffeemaschine.IMenu
  kaffeemaschine.ZutatenBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.ZutatenBehaelter -up-|> kaffeemaschine.AbstractBehaelter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
