@startuml

title __KAFFEEMASCHINE's Class Diagram__\n

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.AbfallBehaelterTest {
        + after()
        + before()
        + testToStringTextausgabeMitFuellstand0()
        + testToStringTextausgabeMitFuellstand50()
        + testWartungAbfallBehaelterFuellstand1()
        + testWartungAbfallBehaelterRueckgabeString()
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.MenuTest {
        + after()
        + before()
        + testMenuCheckMenuKorrekt()
        + testProgrammAuswahlScannerInput_5()
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.StarteKaffeeMaschineTest {
        + after()
        + before()
        + testMain()
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.ZutatenBehaelterTest {
        + after()
        + before()
        + testAbfallBehaelterVollException()
        + testFuellstandRundenAufKorrekteAusgabe()
        + testFuellstandRundenAufKorrekteAusgabeDoubleLenght1()
        + testFuellstandRundenAufKorrekteAusgabeDoubleLenght3()
        + testFuellstandRundenAufKorrekteAusgabeDoubleLenght4()
        + testToStringBehaelterKaffeeFuellstand0()
        + testToStringBehaelterKaffeeFuellstand05()
        + testToStringBehaelterKakaoFuellstand0()
        + testToStringBehaelterKakaoFuellstand05()
        + testToStringBehaelterMilchFuellstand0()
        + testToStringBehaelterMilchFuellstand05()
        + testToStringBehaelterWasserFuellstand0()
        + testToStringBehaelterWasserFuellstand05()
        + testToStringBehaelterZuckerFuellstand0()
        + testToStringBehaelterZuckerFuellstand05()
        + testWartungBehaelterKaffeeFuellstand1()
        + testWartungBehaelterKaffeeRueckgabeString()
        + testWartungBehaelterKakaoFuellstand1()
        + testWartungBehaelterKakaoRueckgabeString()
        + testWartungBehaelterMilchFuellstand1()
        + testWartungBehaelterMilchRueckgabeString()
        + testWartungBehaelterWasserFuellstand10()
        + testWartungBehaelterWasserRueckgabeString()
        + testWartungBehaelterZuckerFuellstand1()
        + testWartungBehaelterZuckerRueckgabeString()
        + testZutatLeerException()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
