@startuml

title __GUI's Class Diagram__\n

  namespace gui {
    class gui.KMGui {
        {static} + jLabels : JLabel[]
        {static} - buttonLeerTexte : String[]
        {static} - buttonTexte : String[]
        {static} - buttonliste : JButton[]
        {static} - g : Graphics
        {static} - imageIcons : ImageIcon[]
        {static} - labelTexte : String[]
        {static} - menuAusgaben : JButton
        {static} - menuPanel : JPanel
        {static} - textLabel : ImageIcon
        {static} + createFrame()
        {static} + getButtonLeerTexte()
        {static} + getButtonTexte()
        {static} + getButtonliste()
        {static} + getImageIcons()
        {static} + getMenuAusgaben()
        {static} + getTextLabel()
        {static} + getjLabels()
        {static} + invoke()
        {static} + menuNeuZeichnen()
        {static} + setButtonliste()
        {static} + setImageIcons()
        {static} + setMenuAusgaben()
        {static} + setTextLabel()
        {static} + setjLabels()
        {static} - actionPerformed()
        {static} - createAndSetIcons()
        {static} - createMenuPanel()
        {static} - createRowPanel()
        {static} - erstelleJlabels()
        {static} - legeButtonsAn()
        {static} - setSizeFromOriginal()
        {static} - setSizeFromOriginal()
    }
  }
  

  namespace gui {
    class gui.MenuSchreiber {
        {static} ~ index : int
        - systemMeldung : String[]
        + MenuSchreiber()
        + createAbfallExceptionMessage()
        + createDisplayMessage()
        + getSystemMeldung()
        + loescheLogFiles()
        + schreibeInfoMenuItem()
        + schreibeWartungsinfo()
        + setSystemMeldung()
        {static} + wartungAnfordern()
    }
  }
  

  gui.KMGui .up.|> kaffeemaschine.IMenu


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
