@startuml

title __GUI's Class Diagram__\n

  namespace gui {
    class gui.GuiKaffeeMaschine {
        {static} ~ ausgangsBild : ImageIcon
        {static} ~ backgroundButton : JButton
        {static} ~ bereit : boolean
        {static} ~ mainPanel : JPanel
        {static} ~ menuPanel : JPanel
        {static} ~ sizeHight : int
        {static} ~ sizeWidht : int
        + GuiKaffeeMaschine()
        {static} - createBackgroundPanel()
        {static} - createFrame()
        {static} - createMenuPanel()
        {static} - createPanel()
        {static} - wrapInPanel()
    }
  }
  

  namespace gui {
    class gui.KMGui {
        {static} ~ bildPfad : String
        {static} ~ buttonLeerTexte : String[]
        {static} ~ buttonTexte : String[]
        {static} ~ buttonliste : JButton[]
        {static} ~ imageIcons : ImageIcon[]
        {static} ~ jLabels : JLabel[]
        {static} ~ labelTexte : String[]
        {static} ~ menuPanel : JPanel
        {static} + createFrame()
        {static} + invoke()
        {static} - actionPerformed()
        {static} - createAndSetIcons()
        {static} - createMenuPanel()
        {static} - createRowPanel()
        {static} - erstelleJlabels()
        {static} - legeButtonsAn()
        {static} - menuNeuZeichnen()
        {static} - setSizeFromOriginal()
        {static} - setSizeFromOriginal()
    }
  }
  

  namespace gui {
    class gui.Menu {
        {static} ~ bildPfad : String
        {static} ~ buttonTexte : String[]
        {static} ~ buttonliste : JButton[]
        {static} ~ imageIcons : ImageIcon[]
        {static} + invoke()
        {static} ~ actionPerformed()
        {static} - createAndSetIcons()
        {static} - legeButtonsAn()
        {static} - setSizeFromOriginal()
    }
  }
  

  gui.GuiKaffeeMaschine -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
