@startuml

title __KAFFEEMASCHINE's Class Diagram__\n

  namespace Kaffeemaschine {
    class Kaffeemaschine.Auswahl {
    }
  }
  

  namespace Kaffeemaschine {
    abstract class Kaffeemaschine.Behaelter {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterAbfall {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterKaffee {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterKakao {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterMilch {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterWasser {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterZucker {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.Kaffeemaschine {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.Rezept {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.StarteKaffeeMaschine {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.ZutatenBehaelter {
    }
  }
  

  Kaffeemaschine.BehaelterAbfall -up-|> Kaffeemaschine.Behaelter
  Kaffeemaschine.BehaelterKaffee -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterKakao -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterMilch -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterWasser -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterZucker -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.ZutatenBehaelter -up-|> Kaffeemaschine.Behaelter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
