@startuml

title __KAFFEEMASCHINE's Class Diagram__\n

  namespace Kaffeemaschine {
    class Kaffeemaschine.Auswahl {
    }
  }
  

  namespace Kaffeemaschine {
    abstract class Kaffeemaschine.AbstractBehaelter {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterAbfall {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterKaffee {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterKakao {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterMilch {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterWasser {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.BehaelterZucker {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.Kaffeemaschine {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.Rezept {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.StarteKaffeeMaschine {
    }
  }
  

  namespace Kaffeemaschine {
    interface Kaffeemaschine.IWartbar {
    }
  }
  

  namespace Kaffeemaschine {
    class Kaffeemaschine.ZutatenBehaelter {
    }
  }
  

  Kaffeemaschine.AbstractBehaelter .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterAbfall .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterAbfall -up-|> Kaffeemaschine.AbstractBehaelter
  Kaffeemaschine.BehaelterKaffee .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterKaffee -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterKakao .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterKakao -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterMilch .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterMilch -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterWasser .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterWasser -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.BehaelterZucker .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.BehaelterZucker -up-|> Kaffeemaschine.ZutatenBehaelter
  Kaffeemaschine.ZutatenBehaelter .up.|> Kaffeemaschine.IWartbar
  Kaffeemaschine.ZutatenBehaelter -up-|> Kaffeemaschine.AbstractBehaelter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
