@startuml

title __KAFFEEMASCHINE's Class Diagram__\n

  namespace kaffeemaschine {
    class kaffeemaschine.AbfallBehaelter {
    }
  }
  

  namespace kaffeemaschine {
    abstract class kaffeemaschine.AbstractBehaelter {
    }
  }
  

  namespace kaffeemaschine {
    interface kaffeemaschine.IMenu {
    }
  }
  

  namespace kaffeemaschine {
    interface kaffeemaschine.IWartbar {
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Kaffeemaschine {
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Menu {
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.Rezept {
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.StarteKaffeeMaschine {
    }
  }
  

  namespace kaffeemaschine {
    class kaffeemaschine.ZutatenBehaelter {
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.AbfallBehaelterTest {
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.MenuTest {
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.StarteKaffeeMaschineTest {
    }
  }
  

  namespace test.kaffeemaschine {
    class test.kaffeemaschine.ZutatenBehaelterTest {
    }
  }
  

  kaffeemaschine.AbfallBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.AbfallBehaelter -up-|> kaffeemaschine.AbstractBehaelter
  kaffeemaschine.AbstractBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.Menu .up.|> kaffeemaschine.IMenu
  kaffeemaschine.ZutatenBehaelter .up.|> kaffeemaschine.IWartbar
  kaffeemaschine.ZutatenBehaelter -up-|> kaffeemaschine.AbstractBehaelter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
